market/apps/allorder/urls.py
from django.conf.urls import url

from apps.allorder.views import allorder, gladdress, address, delAddress, EditAddress, defaAddress, Tureorder, Order, \
    pay, success

urlpatterns = [
    url(r'^$', allorder, name="订单"),  # 订单管理
    url(r'^gladdress/$', gladdress, name="gladdress"),  # 管理收货地址页面
    url(r'^address/$', address, name="address"),  # 增加收货地址页面
    url(r'^editAddress/(?P<id>\d+)/$', EditAddress.as_view(), name="editAddress"),  # 编辑收货地址页面
    url(r'^delAddress/$', delAddress, name="delAddress"),  # 删除收货地址
    url(r'^defaAddress/$', defaAddress, name="defaAddress"),  # 设置为默认收货地址
    url(r'^tureorder/$', Tureorder.as_view(), name="tureorder"),  # 确认订单
    url(r'^order/$', Order.as_view(), name="order"),  # 展示付款
    url(r'^pay/$', pay, name="pay"),  # 发起支付
    url(r'^success/$', success, name="success")  # 支付成功
]

market/apps/cart/urls.py
from django.conf.urls import url

from apps.cart.views import Addcart, cart, CartAdd, CartReduce

urlpatterns = [
    url(r'^addCart/$', Addcart.as_view(), name="addCart"),  # 商品详情页添加购物车
    url(r'^CartADD/$', CartAdd.as_view(), name="CartAdd"),  # 购物车添加
    url(r'^CartReduce/$', CartReduce.as_view(), name="CartReduce"),  # 购物车减少
    url(r'^$', cart, name="cart"),
]

market/apps/goods/urls.py
from django.conf.urls import url

from apps.goods.views import index, detail, category
from django.views.decorators.cache import cache_page

# 把主页设置到缓存中

urlpatterns = [
    url(r'^$', cache_page(3600)(index), name="首页"),
    url(r'^(?P<id>\d+).html/$', detail, name="商品详情"),
    url(r'^category/(?P<c_id>\d+)/(?P<order>\d)/$', category, name="超市"),
]

market/apps/users/urls.py
from django.conf.urls import url

from apps.users.views import LoginView, RegisterView, MemberView, InfomationView, ForgetPassView, sendMsg

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登陆
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^forget/$', ForgetPassView.as_view(), name="forget"),  # 忘记密码
    url(r'^member/$', MemberView.as_view(), name="member"),  # 个人中心
    url(r'^info/$', InfomationView.as_view(), name="info"),  # 个人资料
    url(r'^send/$', sendMsg, name="sendMsg"),  # 发送短信
]

market/goods/urls.py
from django.conf.urls import url

from goods.views import index, detail

urlpatterns = [
    url(r'^$', index, name="首页"),
    url(r'^detail/$', detail, name="商品详情"),
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^users/', include("apps.users.urls", namespace="users")),  # 用户
    url(r'', include("apps.goods.urls", namespace="goods")),  # 商品
    url(r'^cart/', include("apps.cart.urls", namespace="cart")),  # 购物车
    url(r'^allorder/', include("apps.allorder.urls", namespace="allorder")),  # 订单
]

market/apps/goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from db.base_model import BaseModel

# 轮播表
from market import settings


class LunBo(BaseModel):
    name = models.CharField(max_length=100, verbose_name="轮播名称")
    goods_sku = models.ForeignKey(to="Goodsku", verbose_name="商品sku")
    pic_url = models.ImageField(upload_to="goods/banner", verbose_name="图片地址")
    order = models.IntegerField(verbose_name="排序")

    class Meta:
        db_table = "lunbo"
        verbose_name = "轮播表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 首页活动表
class Active(BaseModel):
    name = models.CharField(max_length=100, verbose_name="名称")
    pic = models.ImageField(upload_to="goods/%Y%m", default="images/s1.png", verbose_name="图片")
    url = models.CharField(max_length=200, default="", verbose_name="url地址")

    class Meta:
        db_table = "active"
        verbose_name = "首页活动表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 特色专区表
class AreaGoods(BaseModel):
    name = models.CharField(max_length=100, verbose_name="名称")
    script = models.CharField(max_length=200, verbose_name="描述")
    order = models.IntegerField(verbose_name="排序")
    is_sale = models.BooleanField(default=1, verbose_name="是否上架")

    class Meta:
        db_table = "areaGoods"
        verbose_name = "特色专区表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 专区商品表
class Produce(BaseModel):
    area_id = models.ForeignKey(to="AreaGoods", verbose_name="特色专区id")
    goods_id = models.ForeignKey(to="Goodsku", verbose_name="商品sku表id")

    class Meta:
        db_table = "produce"
        verbose_name = "专区商品表"
        verbose_name_plural = verbose_name

    # def __str__(self):
    #     return self.area_id


# 商品分类表
class Assortment(BaseModel):
    name = models.CharField(max_length=100, verbose_name="分类名")
    introduce = models.CharField(max_length=200, verbose_name="分类简介")
    order = models.IntegerField(default=0, verbose_name="排序")

    class Meta:
        db_table = "assortment"
        verbose_name = "商品分类表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 商品spu表
class Good(BaseModel):
    name = models.CharField(max_length=100, verbose_name="商品名称")
    detail = RichTextUploadingField(verbose_name="商品详情")

    class Meta:
        db_table = "good"
        verbose_name = "商品spu表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 商品sku表
class Goodsku(BaseModel):
    unit_choices = (
        (1, "件"),
        (2, "斤"),
        (3, "箱"),
    )
    name = models.CharField(max_length=100, verbose_name="商品名称")
    introduce = models.CharField(max_length=200, default="", verbose_name="商品简介")
    unit = models.IntegerField(choices=unit_choices, verbose_name="单位")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="商品价格")
    stock = models.IntegerField(default=0, verbose_name="库存")
    sale_num = models.IntegerField(default=0, verbose_name="销量")
    logo_url = models.ImageField(upload_to="goods/%Y%m", default="", verbose_name="logo地址")
    isGround = models.BooleanField(default=True, verbose_name="是否上架")
    assortment_id = models.ForeignKey(to="Assortment", default=0, verbose_name="商品分类id")
    good_id = models.ForeignKey(to="Good", default=0, verbose_name="商品spu表id")

    class Meta:
        db_table = "goods"
        verbose_name = "商品sku表"
        verbose_name_plural = verbose_name

    def show_logo(self):
        return "<img style='width: 50px' src='{}{}' />".format(settings.MEDIA_URL, self.logo_url)

    show_logo.allow_tags = True
    show_logo.short_description = "LOGO"

    def __str__(self):
        return self.name


# 商品相册表
class GoodPic(BaseModel):
    pic_url = models.ImageField(upload_to="goods/pic", verbose_name="图片地址")
    good_id = models.ForeignKey(to="Goodsku", verbose_name="商品id")

    class Meta:
        db_table = "goods_pic"
        verbose_name = "商品相册表"
        verbose_name_plural = verbose_name

    # def __str__(self):
    #     return self.good_id


# 评论表
class Comment(BaseModel):
    name = models.CharField(max_length=30, default="", verbose_name="买家名")
    content = models.CharField(max_length=200, default="", null=True, verbose_name="评论内容")
    parent = models.ForeignKey(to="Goodsku", verbose_name="商品skuid")

    class Meta:
        db_table = "comment"
        verbose_name = "评论表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content

market/apps/users/views.py
import random
import re
import uuid

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View

from apps.users.forms import RegForm, LoadForm, RorgetForm, AddressForm
from apps.users.helper import set_password, login, verify_login_required, send_sms
from apps.users.models import Users, Infor, UserAddress
from django_redis import get_redis_connection
from db.base_model import BaseVerifyView


class RegisterView(View):
    """注册"""

    def get(self, request):
        return render(request, "users/reg.html")

    def post(self, request):
        datas = request.POST
        form = RegForm(datas)
        # 表单验证
        if form.is_valid():
            datas = form.cleaned_data
            # 注册并保存到数据库
            username = datas.get("username")
            pwd = datas.get("password")
            pwd = set_password(pwd)
            Users.objects.create(username=username, password=pwd)
            return redirect("users:login")
        else:
            # 验证失败,返回错误信息
            context = {
                "errors": form.errors,
                "datas": datas
            }
            return render(request, "users/reg.html", context)


def send_phone_code(request):
    """短信验证"""
    try:
        # 获取手机号码
        phone = request.GET.get('phone')
        # 验证手机号码格式
        phone_v = re.compile('^1[3-9]\d{9}$')
        rs = re.search(phone_v, phone)
        if rs:
            # 格式正确,生成随机验证码
            code = "".join([str(random.randint(0, 9)) for _ in range(4)])
            # 将验证码保存到redis中
            r = get_redis_connection("default")
            r.set(phone, code)
            r.expire(phone, 120)

            # 发送短信验证(注释后以便测试)
            print(code)
            # __business_id = uuid.uuid1()
            # # print(__business_id)
            # params = "{\"code\":\"%s\",\"product\":\"校园超市\"}" % code
            # # params = u'{"name":"wqb","code":"12345678","address":"bz","phone":"13000000000"}'
            # print(send_sms(__business_id, phone, "注册验证", "SMS_2245271", params))

            # 验证成功
            return {'ok': 1, 'code': 200}
        else:
            # 验证失败
            return {'ok': 0, 'code': 500, 'msg': '手机号码格式错误！'}
    except:
        # 没有获取到手机号
        return {'ok': 0, 'code': 500, 'msg': '短信验证码发送失败'}


# 短信发送 视图函数
def sendMsg(request):
    return JsonResponse(send_phone_code(request))


class LoginView(View):
    """登陆"""

    def get(self, request):
        # 创建登陆表单对象
        login_form = LoadForm()
        return render(request, "users/login.html", {'form': login_form})

    def post(self, request):
        data = request.POST
        form = LoadForm(data)
        # 表单验证
        if form.is_valid():
            # 验证成功后将登陆标识放到session中
            user = form.cleaned_data.get('user')
            # 调用登陆的方法,放在helper模块中的
            login(request, user)

            # 登陆成功返回之前页面
            next = request.GET.get("next")
            if next:
                return redirect(next)

            # 跳转到用户中心页面
            return redirect('users:member')
        else:
            context = {
                "errors": form.errors
            }
            return render(request, "users/login.html", context)


class ForgetPassView(View):
    def get(self, request):
        return render(request, "users/forgetpassword.html")

    def post(self, request):
        datas = request.POST
        form = RorgetForm(datas)
        # 表单验证
        if form.is_valid():
            datas = form.cleaned_data
            # 修改并保存到数据库
            username = datas.get("username")
            pwd = datas.get("password")
            pwd = set_password(pwd)
            Users.objects.filter(username=username).update(password=pwd)
            return redirect("users:login")
        else:
            # 验证失败,返回错误信息
            context = {
                "errors": form.errors,
                "datas": datas
            }
            return render(request, "users/forgetpassword.html", context)


class MemberView(BaseVerifyView):
    """个人中心"""

    def get(self, request):
        username = request.session.get("username")
        id = request.session.get("ID")
        data = Infor.objects.filter(num_id=id).first()
        print(data)
        context = {
            "username": username,
            "data": data
        }
        return render(request, "users/member.html", context)


class InfomationView(BaseVerifyView):
    """个人资料"""

    def get(self, request):
        id = request.session.get("ID")
        # 捕获异常,有数据就回显,没有数据则显示添加数据的提示信息
        try:
            info = Infor.objects.get(num_id=id)
        except:
            return render(request, "users/infor.html")
        context = {
            "info": info
        }
        return render(request, "users/infor.html", context)

    def post(self, request):
        # 获取post中表单提交的数据
        data = request.POST
        nickname = data.get("nickname")
        sex = data.get("sex")
        birthday = data.get("birthday")
        school = data.get("school")
        address = data.get("address")
        hometown = data.get("hometown")
        phone = data.get("phone")
        id = request.session.get("ID")
        # 获取头像地址
        head = request.FILES.get("head")
        # head = str(he)
        print(head)
        info = Infor.objects.filter(num_id=id).first()
        # 判断是否填写过个人资料,填写过再提交便做更新,否则创建
        if info:
            # Infor.objects.filter(num_id=id).update(head=head, nickname=nickname, sex=sex, birthday=birthday,
            #                                        school=school,
            #                                        address=address, hometown=hometown, phone=phone, num_id=id)
            if head:
                info.head = head
                info.nickname = nickname
                info.sex = sex
                info.birthday = birthday
                info.school = school
                info.address = address
                info.hometown = hometown
                info.phone = phone
                info.save()
            else:
                info.nickname = nickname
                info.sex = sex
                info.birthday = birthday
                info.school = school
                info.address = address
                info.hometown = hometown
                info.phone = phone
                info.save()
            return redirect("users:member")
        else:
            Infor.objects.create(head=head, nickname=nickname, sex=sex, birthday=birthday, school=school,
                                 address=address,
                                 hometown=hometown, phone=phone, num_id=id)
            return redirect("users:member")

market/users/views.py
import hashlib

from django.shortcuts import render, redirect

# Create your views here.
from users.forms import RegForm, LoadForm
from users.models import Users


def register(request):
    if request.method == "GET":
        # 显示注册页面
        return render(request, "users/reg.html")
    else:
        datas = request.POST
        form = RegForm(datas)
        # 表单验证
        if form.is_valid():
            datas = form.cleaned_data
            # 注册并保存到数据库
            username = datas.get("username")
            pwd = datas.get("password")
            ha = hashlib.md5(pwd.encode("utf-8"))
            pwd = ha.hexdigest()
            user = Users.objects.filter(username=username)
            if user:
                return render(request, "users/reg.html")
            else:
                Users.objects.create(username=username, password=pwd)
                return redirect("users:登陆")
        else:
            context = {
                "errors": form.errors,
                "datas": datas
            }
            return render(request, "users/reg.html", context)


def load(request):
    if request.method == "GET":
        return render(request, "users/login.html")
    else:
        data = request.POST
        form = LoadForm(data)
        # 表单验证
        if form.is_valid():
            data = form.cleaned_data
            username = data.get("username")
            pwd = data.get("password")
            try:
                user = Users.objects.get(username=username)
            except Users.MultipleObjectsReturned:
                # 获取多个记录
                return redirect("users:登陆")
            except Users.DoesNotExist:
                return redirect("users:登陆")
            ha = hashlib.md5(pwd.encode("utf-8"))
            pwd = ha.hexdigest()
            # 验证账户
            if pwd == user.password:
                request.session["ID"] = user.id
                request.session["username"] = user.username
                return redirect("users:首页")
            else:
                return redirect("users:登陆")
        else:
            context = {
                "errors": form.errors,
                "data": data
            }
            return render(request, "users/login.html", context)

market/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>超市</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    {#        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">#}
    <link href="{% static 'css/amazeui.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'js/time.js' %}"></script>
</head>
<body>
<header data-am-widget="header" class="am-header am-header-default sq-head ">
    <div class="am-header-left am-header-nav">
        <a href="javascript:history.back()" class="">
            <i class="am-icon-chevron-left"></i>
        </a>
    </div>
    <h1 class="am-header-title">
        <a href="{% url 'users:login' %}" class="">登录</a>
    </h1>
</header>
<div style="height: 49px;"></div>
<!--<div class="login-logo">
    <img src="images/logo.png" />
</div>-->
<div style="height: 3rem;"></div>
<form action="" method="post">
    {% csrf_token %}
    <input type="text" name="username" id="mobile" placeholder="请输入手机号码" class="login-name" value="{{ data.username }}">
    <p class="am-text-danger">{{ errors.username.0 }}</p>
    <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">
    <p class="am-text-danger">{{ errors.password.0 }}</p>
    <input type="submit" class="login-btn" value="我要登录">
</form>
<div class="agree">
    <a href="{% url 'users:register' %}">免费注册</a>
    <a href="{% url 'users:forget' %}" class="forget">忘记密码？</a>
</div>
<div class="line"></div>
<div class="line-text">第三方账号登录</div>
<ul class="second-login">
    <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
    <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
    <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
</ul>
</body>
</html>

market/templates/users/member.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>超市</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    {#        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">#}
    <link href="{% static 'css/amazeui.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'js/popup.mini.js' %}"></script>
</head>
<body style="background: #f6f6f6;">
<header data-am-widget="header" class="am-header am-header-default sq-head ">
    <h1 class="am-header-title">
        <a href="" class="">个人中心</a>
    </h1>
</header>
<div style="height: 49px;"></div>
<div class="member">
    {% if username %}
        <div class="mem-tit">{{ username }}
            <a href="../step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
        </div>
        <div class="mem-pic">
            {#        {% static 'images/memtx.png' %}#}
            <div class="mem-pic-bg" style="background-image: url({{ MEDIA_URL }}{{ data.head }});"></div>
        </div>
    {% else %}
        <div class="mem-tit">现在去<a href="{% url 'users:login' %}">登录</a>/<a href="{% url 'users:register' %}">注册</a>
            <a href="../step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
        </div>
        <div class="mem-pic">
            <div class="mem-pic-bg" style="background-image: url({% static 'images/memtx.png' %});"></div>
        </div>
    {% endif %}
    <ul class="member-menu">
        <li>
            <a href="../records.html">
                <p class="yellow">0</p>
                <p class="black">帐户余额 </p>
            </a>
        </li>
        <li>
            <a href="../integral.html">
                <p class="yellow">0</p>
                <p class="black">积分 </p>
            </a>
        </li>
        <li>
            <a href="../yhq.html">
                <p class="yellow">0</p>
                <p class="black">优惠劵 </p>
            </a>
        </li>
        <li>
            <a href="../collect.html">
                <p class="yellow">0</p>
                <p class="black">我的收藏 </p>
            </a>
        </li>
    </ul>
</div>
<div class="user-list">
    <div class="u-list-main">
        <img src="{% static 'images/order-pic.png' %}" width="27"/>
        <span>我的购物订单</span>
        <a href="{% url 'allorder:订单' %}">查看全部订单></a>
    </div>
    <ul class="user-nav">
        <li><a href="../allorder/allorder.html"> <img src="{% static 'images/1-icon.png' %}">
            <p>待付款</p></a></li>
        <li><a href="../allorder/allorder.html"> <img src="{% static 'images/1-icon1.png' %}">
            <p>待收货</p></a></li>
        <li><a href="../allorder/allorder.html"> <img src="{% static 'images/1-icon2.png' %}">
            <p>待评价</p></a></li>
        <li><a href="../allorder/allorder.html"> <img src="{% static 'images/1-icon3.png' %}">
            <p>退换货</p></a></li>
    </ul>
    <div class="u-list-main">
        <img src="{% static 'images/order-my.png' %}" width="27"/>
        <span>帐户与安全</span>
    </div>
    <ul class="user-nav">
        <li><a href="{% url 'users:info' %}"> <img src="{% static 'images/1-icon4.png' %}">
            <p>个人资料</p></a></li>
        <li><a href="{% url 'allorder:gladdress' %}"> <img src="{% static 'images/1-icon5.png' %}">
            <p>收货地址</p></a></li>
        <li><a href="../saftystep.html"> <img src="{% static 'images/1-icon6.png' %}">
            <p>安全设置</p></a></li>
        <li><a href="../money.html"> <img src="{% static 'images/1-icon7.png' %}">
            <p>我的钱包</p></a></li>
    </ul>
</div>
<!--导航-->
<ul class="sq-nav"
    style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
    <li>
        <div class="am-gallery-item">
            <a href="../job.html" class="">
                <img src="{% static 'images/m_03.png' %}"/>
                <p>我要兼职</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="../recommend.html" class="">
                <img src="{% static 'images/m_04.png' %}"/>
                <p>推荐有奖</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="../myrecommend.html" class="">
                <img src="{% static 'images/m_05.png' %}"/>
                <p>我的推荐</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="" class="">
                <img src="{% static 'images/m_06.png' %}"/>
                <p>我的佣金</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="../yhq.html" class="">
                <img src="{% static 'images/m_02.png' %}"/>
                <p>我的红包</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="../message.html" class="">
                <img src="{% static 'images/m_07.png' %}"/>
                <p>我的动态</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
                <img src="{% static 'images/m_08.png' %}"/>
                <p>客服中心</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="" class="">
                <img src="{% static 'images/m_09.png' %}"/>
                <p>安全退出</p>
            </a>
        </div>
    </li>
</ul>
</div>
<!--客服中心-->
<div class="qd-box">
    <div class="popup-title">
        <span>客服中心</span>
        <div class="popup-close"><i class="iconfont">&#xe602</i></div>
    </div>
    <div class="dq-text">
        <a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
            <img src="{% static 'images/contactqq.png' %}" width="50"/>
            <p class="contactqq">联系QQ</p>
        </a>
        <a href="tel:0791-12345678">
            <img src="{% static 'images/contacttele.png' %}" width="50"/>
            <p class="contacttele">呼叫电话</p>
        </a>
    </div>
</div>
<!--客服中心-->
<!--底部-->
<div style="height: 55px;"></div>
<div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
    <ul class="am-navbar-nav am-cf am-avg-sm-5">
        <li>
            <a href="{% url 'goods:首页' %}" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
        </li>
        <li>
            <a href="../message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
        </li>
        <li>
            <a href="{% url 'cart:cart' %}" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
        </li>
        <li>
            <a href="{% url 'allorder:订单' %}" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
        </li>

        <li>
            <a href="{% url 'users:member' %}" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
        </li>
    </ul>
</div>

<script type='text/javascript'>
    (function () {
        new PopUp_api({el: '.index-qd', html: '.qd-box'});
    })()
</script>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/amazeui.min.js' %}"></script>
</body>
</html>