market/apps/allorder/urls.py
from django.conf.urls import url

from apps.allorder.views import allorder, gladdress, address, delAddress, EditAddress, defaAddress, Tureorder, Order, \
    pay, success

urlpatterns = [
    url(r'^$', allorder, name="订单"),  # 订单管理
    url(r'^gladdress/$', gladdress, name="gladdress"),  # 管理收货地址页面
    url(r'^address/$', address, name="address"),  # 增加收货地址页面
    url(r'^editAddress/(?P<id>\d+)/$', EditAddress.as_view(), name="editAddress"),  # 编辑收货地址页面
    url(r'^delAddress/$', delAddress, name="delAddress"),  # 删除收货地址
    url(r'^defaAddress/$', defaAddress, name="defaAddress"),  # 设置为默认收货地址
    url(r'^tureorder/$', Tureorder.as_view(), name="tureorder"),  # 确认订单
    url(r'^order/$', Order.as_view(), name="order"),  # 展示付款
    url(r'^pay/$', pay, name="pay"),  # 发起支付
    url(r'^success/$', success, name="success")  # 支付成功
]

market/apps/cart/urls.py
from django.conf.urls import url

from apps.cart.views import Addcart, cart, CartAdd, CartReduce

urlpatterns = [
    url(r'^addCart/$', Addcart.as_view(), name="addCart"),  # 商品详情页添加购物车
    url(r'^CartADD/$', CartAdd.as_view(), name="CartAdd"),  # 购物车添加
    url(r'^CartReduce/$', CartReduce.as_view(), name="CartReduce"),  # 购物车减少
    url(r'^$', cart, name="cart"),
]

market/apps/goods/urls.py
from django.conf.urls import url

from apps.goods.views import index, detail, category
from django.views.decorators.cache import cache_page

# 把主页设置到缓存中

urlpatterns = [
    url(r'^$', cache_page(3600)(index), name="首页"),
    url(r'^(?P<id>\d+).html/$', detail, name="商品详情"),
    url(r'^category/(?P<c_id>\d+)/(?P<order>\d)/$', category, name="超市"),
]

market/apps/users/urls.py
from django.conf.urls import url

from apps.users.views import LoginView, RegisterView, MemberView, InfomationView, ForgetPassView, sendMsg

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登陆
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^forget/$', ForgetPassView.as_view(), name="forget"),  # 忘记密码
    url(r'^member/$', MemberView.as_view(), name="member"),  # 个人中心
    url(r'^info/$', InfomationView.as_view(), name="info"),  # 个人资料
    url(r'^send/$', sendMsg, name="sendMsg"),  # 发送短信
]

market/goods/urls.py
from django.conf.urls import url

from goods.views import index, detail

urlpatterns = [
    url(r'^$', index, name="首页"),
    url(r'^detail/$', detail, name="商品详情"),
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^users/', include("apps.users.urls", namespace="users")),  # 用户
    url(r'', include("apps.goods.urls", namespace="goods")),  # 商品
    url(r'^cart/', include("apps.cart.urls", namespace="cart")),  # 购物车
    url(r'^allorder/', include("apps.allorder.urls", namespace="allorder")),  # 订单
]

market/apps/cart/models.py
from django.db import models

market/apps/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from django_redis import get_redis_connection

from apps.goods.models import Goodsku


# 详情页面商品添加到购物车
class Addcart(View):
    def get(self, request):
        return redirect("cart:cart")

    def post(self, request):
        # 判断用户是否登录
        user_id = request.session.get("ID")
        if user_id is None:
            # 没有登录
            return JsonResponse({"code": 1, "errmsg": "没有登录!"})
        num = request.POST.get("num")
        sku_id = request.POST.get("sku_id")
        # 判断参数是否正确
        try:
            num = int(num)
            sku_id = int(sku_id)
        except:
            return JsonResponse({"code": 2, "errmsg": "参数错误"})
        if num <= 0:
            return JsonResponse({"code": 3, "errmsg": "参数错误"})
        # 判断商品是否存在
        try:
            goods = Goodsku.objects.get(pk=sku_id)
        except Goodsku.DoesNotExist:
            return JsonResponse({"code": 4, "errmsg": "商品不存在"})
        # 判断商品是否超过库存
        if num > goods.stock:
            return JsonResponse({"code": 5, "errmsg": "库存不足"})
        # 保存数据到redis中
        r = get_redis_connection('default')
        cart_key = "cart_key_{}".format(user_id)
        r.hincrby(cart_key, sku_id, num)
        return JsonResponse({"code": 0, "msg": "成功"})


# 购物车商品添加
class CartAdd(View):
    def get(self, request):
        redirect("cart:cart")

    def post(self, request):
        # 判断用户是否登录
        user_id = request.session.get("ID")
        if user_id is None:
            # 没有登录
            return JsonResponse({"code": 1, "errmsg": "没有登录!"})
        num = request.POST.get("num")
        sku_id = request.POST.get("sku_id")
        # 判断参数是否正确
        try:
            num = int(num)
            sku_id = int(sku_id)
        except:
            return JsonResponse({"code": 2, "errmsg": "参数错误"})
        if num <= 0:
            return JsonResponse({"code": 3, "errmsg": "参数错误"})
        # 判断商品是否存在
        try:
            goods = Goodsku.objects.get(pk=sku_id)
        except Goodsku.DoesNotExist:
            return JsonResponse({"code": 4, "errmsg": "商品不存在"})
        # 判断商品是否超过库存
        if num > goods.stock:
            return JsonResponse({"code": 5, "errmsg": "库存不足"})
        # 保存数据到redis中
        r = get_redis_connection('default')
        cart_key = "cart_key_{}".format(user_id)
        r.hincrby(cart_key, sku_id, num)
        return JsonResponse({"code": 0, "msg": "成功"})


# 购物车商品减少
class CartReduce(View):
    def get(self, request):
        return redirect("cart:cart")

    def post(self, request):
        # 连接redis
        r = get_redis_connection('default')
        # 判断用户是否登录
        user_id = request.session.get("ID")
        if user_id is None:
            # 没有登录
            return JsonResponse({"code": 1, "errmsg": "没有登录!"})
        num = request.POST.get("num")
        sku_id = request.POST.get("sku_id")
        cart_key = "cart_key_{}".format(user_id)

        # 判断是否是分类页商品减少
        if num == "-1":
            int(num)
            r.hincrby(cart_key, sku_id, num)
            return JsonResponse({"code": 6, "msg": "成功"})

        # 判断参数是否正确
        try:
            num = int(num)
            sku_id = int(sku_id)
        except:
            return JsonResponse({"code": 2, "errmsg": "参数错误"})
        if num <= 0 or num == None:
            r.hdel(cart_key, sku_id)
            return JsonResponse({"code": 3, "errmsg": "参数错误"})
        # 判断商品是否存在
        try:
            goods = Goodsku.objects.get(pk=sku_id)
        except Goodsku.DoesNotExist:
            return JsonResponse({"code": 4, "errmsg": "商品不存在"})
        # 判断商品是否超过库存
        if num > goods.stock:
            return JsonResponse({"code": 5, "errmsg": "库存不足"})
        # 保存数据到redis中
        # r.hset(cart_key, sku_id, num)
        r.hincrby(cart_key, sku_id, num)
        return JsonResponse({"code": 0, "msg": "成功"})


# 渲染购物车
def cart(request):
    user_id = request.session.get("ID")
    r = get_redis_connection("default")
    cart_key = "cart_key_{}".format(user_id)
    data = r.hgetall(cart_key)
    datas = []
    for sku_id, num in data.items():
        sku_id = int(sku_id)
        num = int(num)
        good = Goodsku.objects.get(pk=sku_id)
        good.num = num
        datas.append(good)

    context = {
        "data": datas,
    }
    return render(request, "cart/shopcart.html", context)

market/templates/cart/shopcart.html
{% extends 'public/base.html' %}
{% load static %}
{% block main %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">购物车</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <!--购物车空的状态-->
    {% if not data %}
        <div class="login-logo">
            <img src="{% static 'images/care.png' %}">
            <p>亲、您的购物车还是空空的哦，快去装满它!</p>
            <a href="{% url 'goods:超市' 1 0 %}" class="goshopping">前去逛逛</a>
        </div>
    {% else %}
        <form id="cart" action="{% url 'allorder:tureorder' %}" method="get">
            <ul class="shopcart-list">
                {% for g in data %}
                    <li>
                        <label class="am-checkbox am-warning">
                            <input type="checkbox" checked="checked" name="sku_id" value="{{ g.pk }}" data-am-ucheck>
                        </label>
                        <a href="{% url 'goods:商品详情' g.pk %}"><img src="{{ MEDIA_URL }}{{ g.logo_url }}"
                                                                   class="shop-pic"/></a>
                        <div class="shop-list-mid">
                            <div class="tit"><a
                                    href="{% url 'goods:商品详情' g.pk %}">{{ g.good_id.name }}&emsp;{{ g.name }}</a>
                            </div>
                            <b class="shop-list-price">￥<span class="price">{{ g.price }}</span></b>
                        </div>
                        <div class="list-cart1">
                            <div class="d-stock">
                                <a href="javascript:;" class="decrease">-</a>
                                <input id="" readonly="" sku_id="{{ g.pk }}" class="text_box num" name="" type="text"
                                       value="{{ g.num }}">
                                <a href="javascript:;" class="increase">+</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
                <div style="height: 10px; background: #eee;"></div>
            </ul>
        </form>
        <div class="shop-fix">
            <label class="am-checkbox am-warning">
                <input id="check_all" type="checkbox" checked="checked" value="" data-am-ucheck>
            </label>
            <a class="del">全选</a>
            <a href="javascript:;" class="js-btn">去结算</a>
            <div class="js-text">
                <P>合计：￥<b id="count_price">00.00</b></P>
                <p class="js-car">免费配送</p>
            </div>
        </div>
    {% endif %}

    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="../message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="" class="curr">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'allorder:订单' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>
            <li>
                <a href="{% url 'users:member' %}">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}
{% block foot_js %}
    <script>
        //购物数量加减
        $(function () {
            // 增加数量
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                self.siblings('input').val(current_num);
                var sku_id = $(this).prev().attr("sku_id");
                var num = 1;
                $.ajax({
                    type: "POST",
                    url: "{% url 'cart:CartAdd' %}",
                    dataType: "json",
                    data: {
                        "num": num,
                        "csrfmiddlewaretoken": "{{ csrf_token }}",
                        "sku_id": sku_id,
                    },
                    success: function (data) {
                        console.debug(data);
                    }
                });
                totalPrice();
            });
            // 减少数量
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                var sku_id = $(this).next().attr("sku_id");
                if (current_num > 1) {
                    current_num -= 1;
                    self.siblings('input').val(current_num);
                    var num = -1;
                } else if (current_num == 1) {
                    var num = 0;
                    self.parents("li").remove();
                    location.reload()
                }
                //console.debug(sku_id, num);
                $.ajax({
                    type: "POST",
                    url: "{% url 'cart:CartReduce' %}",
                    dataType: "json",
                    data: {
                        "num": num,
                        "sku_id": sku_id,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    },
                    success: function (data) {
                        console.debug(data);
                    }
                });
                totalPrice();
            });

            // 定义一个计算总价的函数
            function totalPrice() {
                var checkboxes = $(".shopcart-list").find(":checked");
                // 遍历所有被选中的复选框
                var count_price = 0;
                $.each(checkboxes, function (i, e) {
                    //console.debug(i, e)
                    var price = $(e).parents("li").find(".price").text();
                    var num = $(e).parents("li").find(".num").val();
                    count_price += price * num;
                });
                $("#count_price").text(count_price.toFixed(2))
            }

            // 全选框
            $("#check_all").on("change", function () {
                var status = $(this).prop("checked");
                $(".shopcart-list").find(":checkbox").prop("checked", status);
                // 重新定价
                totalPrice();
            });

            // 商品列表复选框
            $(".shopcart-list").find(":checkbox").on("change", function () {
                // 重新定价
                totalPrice();
                if ($(".shopcart-list").find(":checkbox").length == $(".shopcart-list").find(":checked").length) {
                    $("#check_all").prop("checked", true)
                } else {
                    $("#check_all").prop("checked", false)
                }
            });

            // 调用函数
            totalPrice();

            // 绑定结算
            $(".js-btn").on("click", function () {
                if ($(".shopcart-list").find(":checked").length > 0) {
                    $("#cart").submit();
                } else {
                    alert("请选择商品")
                }

            })
        });
    </script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>
{% endblock %}