market/apps/cart/urls.py
from django.conf.urls import url

from apps.cart.views import Addcart, cart, CartAdd, CartReduce

urlpatterns = [
    url(r'^addCart/$', Addcart.as_view(), name="addCart"),  # 商品详情页添加购物车
    url(r'^CartADD/$', CartAdd.as_view(), name="CartAdd"),  # 购物车添加
    url(r'^CartReduce/$', CartReduce.as_view(), name="CartReduce"),  # 购物车减少
    url(r'^$', cart, name="cart"),
]

market/apps/goods/urls.py
from django.conf.urls import url

from apps.goods.views import index, detail, category
from django.views.decorators.cache import cache_page

# 把主页设置到缓存中

urlpatterns = [
    url(r'^$', cache_page(3600)(index), name="首页"),
    url(r'^(?P<id>\d+).html/$', detail, name="商品详情"),
    url(r'^category/(?P<c_id>\d+)/(?P<order>\d)/$', category, name="超市"),
]

market/apps/users/urls.py
from django.conf.urls import url

from apps.users.views import LoginView, RegisterView, MemberView, InfomationView, ForgetPassView, sendMsg

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登陆
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^forget/$', ForgetPassView.as_view(), name="forget"),  # 忘记密码
    url(r'^member/$', MemberView.as_view(), name="member"),  # 个人中心
    url(r'^info/$', InfomationView.as_view(), name="info"),  # 个人资料
    url(r'^send/$', sendMsg, name="sendMsg"),  # 发送短信
]

market/goods/urls.py
from django.conf.urls import url

from goods.views import index, detail

urlpatterns = [
    url(r'^$', index, name="首页"),
    url(r'^detail/$', detail, name="商品详情"),
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^users/', include("apps.users.urls", namespace="users")),  # 用户
    url(r'', include("apps.goods.urls", namespace="goods")),  # 商品
    url(r'^cart/', include("apps.cart.urls", namespace="cart")),  # 购物车
    url(r'^allorder/', include("apps.allorder.urls", namespace="allorder")),  # 订单
]

market/apps/goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from db.base_model import BaseModel

# 轮播表
from market import settings


class LunBo(BaseModel):
    name = models.CharField(max_length=100, verbose_name="轮播名称")
    goods_sku = models.ForeignKey(to="Goodsku", verbose_name="商品sku")
    pic_url = models.ImageField(upload_to="goods/banner", verbose_name="图片地址")
    order = models.IntegerField(verbose_name="排序")

    class Meta:
        db_table = "lunbo"
        verbose_name = "轮播表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 首页活动表
class Active(BaseModel):
    name = models.CharField(max_length=100, verbose_name="名称")
    pic = models.ImageField(upload_to="goods/%Y%m", default="images/s1.png", verbose_name="图片")
    url = models.CharField(max_length=200, default="", verbose_name="url地址")

    class Meta:
        db_table = "active"
        verbose_name = "首页活动表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 特色专区表
class AreaGoods(BaseModel):
    name = models.CharField(max_length=100, verbose_name="名称")
    script = models.CharField(max_length=200, verbose_name="描述")
    order = models.IntegerField(verbose_name="排序")
    is_sale = models.BooleanField(default=1, verbose_name="是否上架")

    class Meta:
        db_table = "areaGoods"
        verbose_name = "特色专区表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 专区商品表
class Produce(BaseModel):
    area_id = models.ForeignKey(to="AreaGoods", verbose_name="特色专区id")
    goods_id = models.ForeignKey(to="Goodsku", verbose_name="商品sku表id")

    class Meta:
        db_table = "produce"
        verbose_name = "专区商品表"
        verbose_name_plural = verbose_name

    # def __str__(self):
    #     return self.area_id


# 商品分类表
class Assortment(BaseModel):
    name = models.CharField(max_length=100, verbose_name="分类名")
    introduce = models.CharField(max_length=200, verbose_name="分类简介")
    order = models.IntegerField(default=0, verbose_name="排序")

    class Meta:
        db_table = "assortment"
        verbose_name = "商品分类表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 商品spu表
class Good(BaseModel):
    name = models.CharField(max_length=100, verbose_name="商品名称")
    detail = RichTextUploadingField(verbose_name="商品详情")

    class Meta:
        db_table = "good"
        verbose_name = "商品spu表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 商品sku表
class Goodsku(BaseModel):
    unit_choices = (
        (1, "件"),
        (2, "斤"),
        (3, "箱"),
    )
    name = models.CharField(max_length=100, verbose_name="商品名称")
    introduce = models.CharField(max_length=200, default="", verbose_name="商品简介")
    unit = models.IntegerField(choices=unit_choices, verbose_name="单位")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="商品价格")
    stock = models.IntegerField(default=0, verbose_name="库存")
    sale_num = models.IntegerField(default=0, verbose_name="销量")
    logo_url = models.ImageField(upload_to="goods/%Y%m", default="", verbose_name="logo地址")
    isGround = models.BooleanField(default=True, verbose_name="是否上架")
    assortment_id = models.ForeignKey(to="Assortment", default=0, verbose_name="商品分类id")
    good_id = models.ForeignKey(to="Good", default=0, verbose_name="商品spu表id")

    class Meta:
        db_table = "goods"
        verbose_name = "商品sku表"
        verbose_name_plural = verbose_name

    def show_logo(self):
        return "<img style='width: 50px' src='{}{}' />".format(settings.MEDIA_URL, self.logo_url)

    show_logo.allow_tags = True
    show_logo.short_description = "LOGO"

    def __str__(self):
        return self.name


# 商品相册表
class GoodPic(BaseModel):
    pic_url = models.ImageField(upload_to="goods/pic", verbose_name="图片地址")
    good_id = models.ForeignKey(to="Goodsku", verbose_name="商品id")

    class Meta:
        db_table = "goods_pic"
        verbose_name = "商品相册表"
        verbose_name_plural = verbose_name

    # def __str__(self):
    #     return self.good_id


# 评论表
class Comment(BaseModel):
    name = models.CharField(max_length=30, default="", verbose_name="买家名")
    content = models.CharField(max_length=200, default="", null=True, verbose_name="评论内容")
    parent = models.ForeignKey(to="Goodsku", verbose_name="商品skuid")

    class Meta:
        db_table = "comment"
        verbose_name = "评论表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content

market/goods/models.py
from django.db import models


# Create your models here.
class Goods(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    time = models.DateField(auto_now=True)
    url = models.CharField(max_length=100, default="")

    class Meta:
        db_table = "goods"

    def __str__(self):
        return self.name


class Comment(models.Model):
    name = models.CharField(max_length=30, default="")
    content = models.CharField(max_length=200, default="", null=True)
    time = models.DateField(auto_now_add=True)
    parent = models.ForeignKey(to="Goods")

    class Meta:
        db_table = "comment"

    def __str__(self):
        return self.content

market/apps/goods/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect
from apps.goods.models import Goodsku, Comment, Active, Assortment, LunBo, AreaGoods
from django_redis import get_redis_connection


def index(request):
    active = Active.objects.all()
    lunbo = LunBo.objects.all()
    areas = AreaGoods.objects.all()
    context = {
        "active": active,
        "lunbo": lunbo,
        "areas": areas,
    }
    return render(request, "users/index.html", context)


def detail(request, id):
    try:
        data = Goodsku.objects.get(id=id)
    except Goodsku.DoesNotExist:
        return redirect("goods:首页")
    except ValueError:
        return redirect("goods:首页")
    # 在数据库中查询id对应的商品
    comment = Comment.objects.filter(parent_id=id)
    context = {
        "goods": data,
        "comment": comment
    }
    return render(request, "goods/detail.html", context)


def category(request, c_id, order):
    """
    排序规则:综合(0),销量(1),价格降(2),价格升(3),新品(4)
    """
    c_id = int(c_id)
    order = int(order)
    user_id = request.session.get("ID")
    # 获取分类
    assort = Assortment.objects.filter(isDelete=False).order_by("-order")
    # 查询分类下的商品 默认查询第一个分类
    if c_id == 0:
        ass = assort.first()
        c_id = ass.pk
    goods = Goodsku.objects.filter(isDelete=False, isGround=True, assortment_id=c_id)
    or_list = ["id", "-sale_num", "-price", "price", "time"]
    try:
        one = or_list[order]
    except:
        one = or_list[0]
        order = 0
    goods = goods.order_by(one)

    # 分页
    pageSize = 10  # 每页显示条数
    paginator = Paginator(goods, pageSize)  # 获取分页对象
    # 获取分页数据
    p = request.GET.get('p', 1)  # 获取当前页,默认1
    try:
        page = paginator.page(p)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        page = paginator.page(1)

    # 连接redis查询商品总数量
    r = get_redis_connection("default")
    cart_key = "cart_key_{}".format(user_id)
    data = r.hgetall(cart_key)
    count = 0
    for sku_id, num in data.items():
        sku_id = int(sku_id)
        num = int(num)
        count += num
    # 渲染页面
    context = {
        "assort": assort,
        "goods": page,
        "c_id": c_id,
        "order": order,
        "num": count
    }
    return render(request, "goods/category.html", context)

market/goods/views.py
from django.shortcuts import render

# Create your views here.
from goods.models import Goods, Comment


def index(request):
    data = Goods.objects.all()
    context = {
        "goods": data
    }
    return render(request, "users/index.html", context)


def detail(request):
    try:
        id = request.GET.get("id")
        data = Goods.objects.get(id=id)
    except Goods.DoesNotExist:
        id = 1
        data = Goods.objects.get(id=id)
    except ValueError:
        id = 1
        data = Goods.objects.get(id=id)
    # 在数据库中查询id对应的商品
    comment = Comment.objects.filter(parent_id=id)
    context = {
        "goods": data,
        "comment": comment
    }
    return render(request, "goods/detail.html", context)

market/templates/goods/category.html
{% extends 'public/base.html' %}
{% load static %}
{% block css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }

        .list-price {
            background: url({% if order == 2 %}{% static 'images/order-bot.png' %}{% elif order == 3 %}{% static 'images/order-top.png' %}{% else %}{% static 'images/order.png' %}{% endif %}) no-repeat right center;
            padding-right: 20px;
            font-style: normal;
        }
    </style>
{% endblock %}

{% block main %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="{% url 'goods:首页' %}" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <div class="cate-search">
            <form action="/search/" method="get">
                <input type="text" class="cate-input" name="q" value="" placeholder="请输入您要的搜索的产品关键词"/>
                <input type="submit" class="cate-btn" value=""/>
            </form>
        </div>
    </header>
    <div style="height: 49px;"></div>
    <ul class="list-nav">
        <li {% if order == 0 %}class="current"{% endif %}><a href="{% url 'goods:超市' c_id 0 %}">综合</a></li>
        <li {% if order == 1 %}class="current"{% endif %}><a href="{% url 'goods:超市' c_id 1 %}">销量</a></li>
        <li {% if order == 3 %}class="current"{% endif %}><a href="{% url 'goods:超市' c_id 3 %}"><i
                class="list-price">价格</i></a></li>
        <li {% if order == 4 %}class="current"{% endif %}><a href="{% url 'goods:超市' c_id 4 %}">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for ass in assort %}
                <li {% if c_id == ass.pk %}class="current"{% endif %}>
                    <a href="{% url 'goods:超市' ass.pk order %}">{{ ass.name }}</a>
                </li>
            {% endfor %}
        </div>
        <div class="list-right">
            <ul class="list-pro">
                {% for good in goods %}
                    <li>
                        <a href="{% url 'goods:商品详情' good.pk %}">
                            <img src="{{ MEDIA_URL }}{{ good.logo_url }}" class="list-pic"/>
                        </a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit">
                                <a href="{% url 'goods:商品详情' good.pk %}">
                                    {{ good.good_id.name }}&emsp;{{ good.name }}
                                </a>
                            </div>
                            <div class="am-gallery-desc">￥{{ good.price }}</div>
                            <p>
                                销量：{{ good.sale_num }}{% if good.unit == 1 %}件{% elif good.unit == 2 %}
                                斤{% elif good.unit == 3 %}箱{% endif %}
                            </p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a href="javascript:;" class="decrease">-</a>
                                <input id="num" readonly="" sku_id="{{ good.pk }}" class="text_box" name="" type="text"
                                       value="0">
                                <a href="javascript:;" class="increase">+</a>
                            </div>
                        </div>
                        <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                    </li>
                {% empty %}
                    <p class="am-btn">此分类下还没有商品哦!~~</p>
                {% endfor %}
            </ul>
            {% if goods.has_previous %}
                <a href="?p={{ goods.previous_page_number }}">上一页</a>
            {% endif %}
            {% if goods.has_next %}
                <a href="?p={{ goods.next_page_number }}">下一页</a>
            {% endif %}
        </div>
    </div>

    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <a href="{% url 'cart:cart' %}">
            <div class="fix-bot-cart"><i class="cart_num">{{ num }}</i></div>
        </a>
        <a href="../allorder/tureorder.html" class="list-js">去结算</a>
        <a href="../allorder/tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}
{% block foot_js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>
    <script>
        //购物数量加减
        $(function () {
            $('.increase').on("click", function () {
                var self = $(this);
                // 改变购物车上的数量显示
                var n = self.parents(".content-list").next().next(".fix-bot").find(".cart_num").text();
                n = parseInt(n) + 1;
                self.parents(".content-list").next().next(".fix-bot").find(".cart_num").text(n);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                if (current_num > 0) {
                    self.siblings(".decrease").fadeIn();
                    self.siblings(".text_box").fadeIn();
                }
                self.siblings('input').val(current_num);
                // 发送ajax请求,保存商品到redis中
                var num = 1;
                var sku_id = self.prev().attr("sku_id");
                $.ajax({
                    type: "POST",
                    url: "{% url 'cart:CartAdd' %}",
                    data: {
                        "num": num,
                        "sku_id": sku_id,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    },
                    success: function (data) {
                        //console.debug(data)
                        if (data.code == 0) {
                            console.debug(data)
                        } else if (data.code == 1) {
                            // 没有登录,询问是否跳转到登陆界面
                            var flag = confirm("您还没有登陆,是否跳转到登陆界面");
                            //console.debug(flag); true
                            if (flag == true) {
                                location.href = "{% url 'users:login' %}?next={% url 'goods:超市' 1 0 %}"
                            }
                        }
                    }
                });
            });

            $('.decrease').on("click", function () {
                var self = $(this);
                // 改变购物车上的数量显示
                var n = self.parents(".content-list").next().next(".fix-bot").find(".cart_num").text();
                n = parseInt(n) - 1;
                self.parents(".content-list").next().next(".fix-bot").find(".cart_num").text(n);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    current_num -= 1;
                    if (current_num < 1) {
                        self.fadeOut();
                        self.siblings(".text_box").fadeOut();
                    }
                    self.siblings('input').val(current_num);
                    // 发送ajax请求,保存商品到redis中
                    var num = -1;
                    var sku_id = self.next().attr("sku_id");
                    $.ajax({
                        type: "POST",
                        url: "{% url 'cart:CartReduce' %}",
                        data: {
                            "num": num,
                            "sku_id": sku_id,
                            "csrfmiddlewaretoken": "{{ csrf_token }}"
                        },
                        success: function (data) {
                            //console.debug(data)
                            if (data.code == 0) {
                                console.debug(data)
                            } else if (data.code == 1) {
                                // 没有登录,询问是否跳转到登陆界面
                                var flag = confirm("您还没有登陆,是否跳转到登陆界面");
                                //console.debug(flag); true
                                if (flag == true) {
                                    location.href = "{% url 'users:login' %}?next={% url 'goods:超市' 1 0 %}"
                                }
                            }else if(data.code == 6){
                                console.debug(data)
                            }
                        }
                    });
                }
            });

            //改变价格上的url地址
            if ("{{ order }}" == 2) {
                $(".list-price").parent("a").attr('href', "{% url 'goods:超市' c_id 3 %}")
            } else if ("{{ order }}" == 3) {
                $(".list-price").parent("a").attr('href', "{% url 'goods:超市' c_id 2 %}")
            }
        })
    </script>
{% endblock %}

market/templates/goods/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>超市</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    {#        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">#}
    <link href="{% static 'css/amazeui.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <script>
        function changeImage() {
            if ($("#imgflag").attr("src") == '{% static 'images/herat.png' %}') {
                document.getElementById("imgflag").src = "{% static 'images/redherat.png' %}";
            } else {
                document.getElementById("imgflag").src = "{% static 'images/herat.png' %}";
            }
        }
    </script>

    <style>
        .am-slider-default .am-control-nav {
            text-align: center;
        }

        .am-slider-default .am-control-nav li a.am-active {
            background: #cb2527;
        }

        .am-slider-default .am-control-nav li a {
            border: 0;
            width: 10px;
            height: 10px;
        }
    </style>
</head>
<body>
<header data-am-widget="header" class="am-header am-header-default sq-head ">
    <div class="am-header-left am-header-nav">
        <a href="javascript:history.back()" class="">
            <i class="am-icon-chevron-left"></i>
        </a>
    </div>
    <h1 class="am-header-title">
        <a href="" class="">商品详情</a>
    </h1>
</header>
<div style="height: 49px;"></div>
<!--图片轮换-->
<div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
    <ul class="am-slides">
        {% for g in goods.goodpic_set.all %}
            <li><img src="{{ MEDIA_URL }}{{ g.pic_url }}" style="height: 334px" draggable="false"/></li>
        {% endfor %}
    </ul>
</div>
<div class="detal-info" style="position: relative; width: 100%;">
    <p>{{ goods.name }}</p>
    <h2>商城价：<span id="price">￥{{ goods.price }}</span></h2>
    <div class="heart">
        <img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()"/>
        <p>收藏</p>
    </div>
</div>
<div class="d-amount">
    <h4>数量：</h4>
    <div class="d-stock">
        <a class="decrease">-</a>
        <input id="num" sku_id="{{ goods.pk }}" readonly="" class="text_box" name="" type="text" value="1">
        <a class="increase">+</a>
    </div>
</div>
<div style="background: #eee; height: 10px;"></div>
<div class="am-tabs detail-list" data-am-tabs>
    <ul class="am-tabs-nav am-nav am-nav-tabs">
        <li class="am-active"><a href="#tab1">商品详情</a></li>
        <li><a href="#tab2">商品评论</a></li>
    </ul>

    <div class="am-tabs-bd">
        <div class="am-tab-panel am-fade am-in am-active detail " id="tab1">
            {{ goods.good_id.detail|safe }}
        </div>
        <div class="am-tab-panel am-fade detail " id="tab2">
            <!--<div class="comment">
                <span>好评：</span>
                <div class="com-good"></div>
                <span>100%</span>
            </div>
            <div class="comment">
                <span>中评：</span>
                <div class="com-bad"></div>
                <span>0%</span>
            </div>
            <div class="comment">
                <span>差评：</span>
                <div class="com-bad"></div>
                <span>0%</span>
            </div>-->
            <ul class="comment-list">
                <li class="current"><a href="">全部</a></li>
                <li><a href="">好评（20）</a></li>
                <li><a href="">中评（5）</a></li>
                <li><a href="">差评（0）</a></li>
            </ul>
            <ul class="comment-pic">
                {% for com in comment %}
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>{{ com.name }}</span>
                            <i> [{{ com.time }}]</i>
                        </div>
                        <div class="comment-con">
                            {{ com.content }}
                        </div>
                    </li>
                {% empty %}
                    <div class="comment-con">
                        还没有人评论
                    </div>
                {% endfor %}
                {#                <li>#}
                {#                    <div class="tit">#}
                {#                        <img src="{% static 'images/tx.png' %}" class="tx"/>#}
                {#                        <span>songke2014</span>#}
                {#                        <i> [2016-01-01]</i>#}
                {#                    </div>#}
                {#                    <div class="comment-con">#}
                {#                        买了些给家人，都说不错！#}
                {#                    </div>#}
                {#                </li>#}
            </ul>
        </div>
    </div>
</div>


<!--底部-->
<div style=" height: 55px;"></div>
<ul class="fix-shopping">
    <li><a href="javascript:;" class="join">加入购物车</a></li>
    <li><a href="../allorder/tureorder.html" class="imm-buy">立即购买</a></li>
</ul>

<script>
    //购物数量加减
    $(function () {
        $('.increase').click(function () {
            var self = $(this);
            var current_num = parseInt(self.siblings('input').val());
            current_num += 1;
            self.siblings('input').val(current_num);
        });
        $('.decrease').click(function () {
            var self = $(this);
            var current_num = parseInt(self.siblings('input').val());
            if (current_num > 1) {
                current_num -= 1;
                self.siblings('input').val(current_num);
            }
        });

        // 绑定ajax点击事件
        $(".join").on("click", function () {
            //console.debug(11);
            var num = $("#num").val();
            var sku_id = $("#num").attr("sku_id");
            //console.debug(num, sku_id);
            $.ajax({
                type: "POST",
                url: "{% url 'cart:addCart' %}",
                data: {
                    "num": num,
                    "sku_id": sku_id,
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                },
                dataType: "json",
                success: function (data) {
                    //console.debug(data);
                    if (data.code == 0) {
                        alert("成功添加到购物车")
                    } else if (data.code == 1) {
                        // 没有登录,询问是否跳转到登陆界面
                        var flag = confirm("您还没有登陆,是否跳转到登陆界面");
                        //console.debug(flag); true
                        if (flag == true) {
                            location.href = "{% url 'users:login' %}?next={% url 'goods:商品详情' goods.pk %}"
                        }
                    }
                }
            })
        })
    })
</script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/amazeui.min.js' %}"></script>
</body>
</html>