market/apps/allorder/urls.py
from django.conf.urls import url

from apps.allorder.views import allorder, gladdress, address, delAddress, EditAddress, defaAddress, Tureorder, Order, \
    pay, success

urlpatterns = [
    url(r'^$', allorder, name="订单"),  # 订单管理
    url(r'^gladdress/$', gladdress, name="gladdress"),  # 管理收货地址页面
    url(r'^address/$', address, name="address"),  # 增加收货地址页面
    url(r'^editAddress/(?P<id>\d+)/$', EditAddress.as_view(), name="editAddress"),  # 编辑收货地址页面
    url(r'^delAddress/$', delAddress, name="delAddress"),  # 删除收货地址
    url(r'^defaAddress/$', defaAddress, name="defaAddress"),  # 设置为默认收货地址
    url(r'^tureorder/$', Tureorder.as_view(), name="tureorder"),  # 确认订单
    url(r'^order/$', Order.as_view(), name="order"),  # 展示付款
    url(r'^pay/$', pay, name="pay"),  # 发起支付
    url(r'^success/$', success, name="success")  # 支付成功
]

market/apps/cart/urls.py
from django.conf.urls import url

from apps.cart.views import Addcart, cart, CartAdd, CartReduce

urlpatterns = [
    url(r'^addCart/$', Addcart.as_view(), name="addCart"),  # 商品详情页添加购物车
    url(r'^CartADD/$', CartAdd.as_view(), name="CartAdd"),  # 购物车添加
    url(r'^CartReduce/$', CartReduce.as_view(), name="CartReduce"),  # 购物车减少
    url(r'^$', cart, name="cart"),
]

market/apps/users/urls.py
from django.conf.urls import url

from apps.users.views import LoginView, RegisterView, MemberView, InfomationView, ForgetPassView, sendMsg

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登陆
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^forget/$', ForgetPassView.as_view(), name="forget"),  # 忘记密码
    url(r'^member/$', MemberView.as_view(), name="member"),  # 个人中心
    url(r'^info/$', InfomationView.as_view(), name="info"),  # 个人资料
    url(r'^send/$', sendMsg, name="sendMsg"),  # 发送短信
]

market/goods/urls.py
from django.conf.urls import url

from goods.views import index, detail

urlpatterns = [
    url(r'^$', index, name="首页"),
    url(r'^detail/$', detail, name="商品详情"),
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^users/', include("apps.users.urls", namespace="users")),  # 用户
    url(r'', include("apps.goods.urls", namespace="goods")),  # 商品
    url(r'^cart/', include("apps.cart.urls", namespace="cart")),  # 购物车
    url(r'^allorder/', include("apps.allorder.urls", namespace="allorder")),  # 订单
]

market/apps/allorder/models.py
from django.db import models

from db.base_model import BaseModel


class Payment(BaseModel):
    """支付方式"""
    pay_name = models.CharField(max_length=20, verbose_name='支付方式')
    img = models.ImageField(upload_to="pay/", default="", verbose_name="支付方式图")

    class Meta:
        db_table = "payment"
        verbose_name = "支付方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.pay_name


class Transport(BaseModel):
    """运输方式"""
    name = models.CharField(max_length=20, verbose_name='配送方式')
    money = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='金额')

    class Meta:
        db_table = "transport"
        verbose_name = "运输方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Orders(BaseModel):
    """订单信息表"""
    status_choices = (
        (0, "代付款"),
        (1, "代发货"),
        (2, "待收货"),
        (3, "待评价"),
        (4, "已完成"),
    )
    user_id = models.ForeignKey(to="users.Users", verbose_name="用户id")
    order_num = models.CharField(max_length=100, verbose_name="订单编号", unique=True)
    name = models.CharField(max_length=100, verbose_name="收货人")
    phone = models.CharField(max_length=100, verbose_name="收货人电话")
    address = models.CharField(max_length=200, verbose_name="订单地址")
    status = models.SmallIntegerField(choices=status_choices, default=0, verbose_name="订单状态")
    transport = models.CharField(max_length=50, verbose_name="运输方式")
    transport_price = models.CharField(max_length=50, verbose_name="运输价格")
    payment = models.ForeignKey(to="Payment", null=True, blank=True, verbose_name="付款方式")
    order_amount = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="商品总价")
    fact_money = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="实际支付")
    comment = models.CharField(max_length=200, null=True, blank=True, verbose_name="备注说明")

    class Meta:
        db_table = "orders"
        verbose_name = "订单信息表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class OrderGoods(BaseModel):
    """订单商品表"""
    order_id = models.ForeignKey(to="Orders", verbose_name="订单id")
    sku_id = models.ForeignKey(to="goods.Goodsku", verbose_name="商品id")
    good_num = models.IntegerField(default=0, verbose_name="商品数量")
    good_price = models.DecimalField(default=0, max_digits=9, decimal_places=2)

    class Meta:
        db_table = "ordergoods"
        verbose_name = "订单商品表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.order_id.name

market/apps/allorder/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views import View

from apps.allorder.models import Transport, Orders, OrderGoods
from apps.goods.models import Goodsku
from apps.users.forms import AddressForm, EditaddressForm
from apps.users.helper import verify_login_required
from apps.users.models import UserAddress
from db.base_model import BaseVerifyView
from django_redis import get_redis_connection
from datetime import datetime
import random
from django.db import transaction
from alipay import AliPay
import os
from django.conf import settings
import time


# 订单页面
def allorder(request):
    return render(request, "allorder/allorder.html")


# 管理收货地址页面
def gladdress(request):
    data = UserAddress.objects.filter(isDelete=False).order_by("-isDefault")
    context = {
        "data": data
    }
    return render(request, "allorder/gladdress.html", context)


# 增加收货地址页面
def address(request):
    if request.method == "POST":
        data = request.POST.dict()
        user_id = request.session.get("ID")
        data["user_id"] = user_id
        form = AddressForm(data)
        # print(data.get("isDefault"))
        if form.is_valid():
            clean_data = form.cleaned_data
            UserAddress.objects.create(user_id=user_id, **clean_data)
            return redirect("allorder:gladdress")
        else:
            # 验证失败,返回错误信息
            context = {
                "form": form,
            }
            return render(request, "allorder/address.html", context)
    else:
        return render(request, "allorder/address.html")


# 编辑收货地址
class EditAddress(BaseVerifyView):

    def get(self, request, id):
        user_id = request.session.get("ID")
        try:
            address = UserAddress.objects.get(user_id=user_id, pk=id)
        except UserAddress.DoesNotExist:
            return redirect("allorder:address")
        context = {
            "address": address
        }
        return render(request, "allorder/editAddress.html", context)

    def post(self, request, id):
        data = request.POST.dict()
        user_id = request.session.get("ID")
        data["user_id"] = user_id
        form = EditaddressForm(data)
        if form.is_valid():
            clean_data = form.cleaned_data
            id = data.get('id')
            UserAddress.objects.filter(user_id=user_id, pk=id).update(**clean_data)
            return redirect("allorder:gladdress")
        else:
            # 验证失败,返回错误信息
            context = {
                "form": form,
                "address": data
            }
            return render(request, "allorder/editAddress.html", context)


# 删除收货地址
def delAddress(request):
    if request.method == "POST":
        id = request.POST.get("id")
        user_id = request.session.get("ID")
        UserAddress.objects.filter(user_id=user_id, pk=id).update(isDelete=True)
        return JsonResponse({"code": 0, "msg": "成功"})
    else:
        return JsonResponse({"code": 1, "errmsg": "参数错误"})


# 设置默认收货地址
def defaAddress(request):
    if request.method == "POST":
        id = request.POST.get("id")
        user_id = request.session.get("ID")
        UserAddress.objects.all().update(isDefault=False)
        UserAddress.objects.filter(user_id=user_id, pk=id).update(isDefault=True)
        return JsonResponse({"code": 0, "msg": "成功"})
    else:
        return JsonResponse({"code": 1, "errmsg": "参数错误"})


# 确认订单页面
class Tureorder(View):
    # 回显确认订单页面
    def get(self, request):
        # 判断是否登录
        user_id = request.session.get("ID")
        if not user_id:
            return redirect("users:login")
        # 获取收货地址对象
        address = UserAddress.objects.filter(user_id=user_id, isDelete=False).order_by("-isDefault").first()
        # 获取商品sku_id
        sku_ids = request.GET.getlist("sku_id")
        # 如果没有,跳转到购物车
        if len(sku_ids) == 0:
            return redirect("cart:cart")
        # 转为整数
        try:
            sku_ids_list = [int(sku_id) for sku_id in sku_ids]
        except:
            return redirect("cart:cart")

        # 准备reids
        r = get_redis_connection("default")
        cart_key = "cart_key_{}".format(user_id)

        # 获取商品信息
        goodskus = []
        total_price = 0
        for sku_id in sku_ids_list:
            goods = Goodsku.objects.get(pk=sku_id)
            try:
                # 获取购物车中的数量
                count = int(r.hget(cart_key, sku_id))
                goods.count = count
            except:
                return redirect("cart:cart")
            # 计算总价
            total_price += goods.price * count
            goodskus.append(goods)

        # 运输方式,价格升序
        transport = Transport.objects.filter(isDelete=False).order_by("money")

        context = {
            "address": address,
            "goodskus": goodskus,
            "total_price": total_price,
            "transport": transport,
        }

        return render(request, "allorder/tureorder.html", context)

    @transaction.atomic
    def post(self, request):
        # 提交订单数据
        # 判断用户是否登录
        user_id = request.session.get("ID")
        if not user_id:
            return JsonResponse({"code": 1, "errmsg": "没有登录!"})
        # 获取数据
        comment = request.POST.get("comment")
        address_id = request.POST.get("address_id")
        transport_id = request.POST.get("transport")
        sku_ids = request.POST.getlist("sku_id")
        # 判断参数是否存在
        if not all([address_id, transport_id, sku_ids]):
            return JsonResponse({"code": 2, "errmsg": "参数错误!"})
        # 判断是否为整数
        try:
            address_id = int(address_id)
            transport_id = int(transport_id)
            sku_ids_int = [int(sku_id) for sku_id in sku_ids]
        except:
            return JsonResponse({"code": 3, "errmsg": "参数错误!"})
        # 判断收货地址和运输方式必须存在
        try:
            address = UserAddress.objects.get(pk=address_id, isDelete=False)
        except UserAddress.DoesNotExist:
            return JsonResponse({"code": 4, "errmsg": "收货地址不存在!"})
        try:
            transport = Transport.objects.get(pk=transport_id, isDelete=False)
        except Transport.DoesNotExist:
            return JsonResponse({"code": 5, "errmsg": "收货地址不存在!"})
        # 将数据保存到订单表中
        # 准备订单编号
        order_num = "{}{}{}".format(datetime.today().strftime("%Y%m%d%H%M%S"), user_id, random.randint(10000, 99999))
        # 准备详细地址
        detail = "{} {} {} {}".format(address.hcity, address.hproper, address.harea, address.brief)

        # 创建事务对象
        sid = transaction.savepoint()

        order = Orders.objects.create(
            user_id_id=user_id,
            order_num=order_num,
            name=address.username,
            phone=address.phone,
            address=detail,
            transport=transport.name,
            transport_price=transport.money,
            comment=comment
        )
        # 连接redis
        cart_key = "cart_key_{}".format(user_id)
        r = get_redis_connection("default")

        # 保存商品总价
        order_amount = 0

        # 遍历商品id
        for sku in sku_ids_int:
            try:
                # select_for_update() 所有匹配的条目将被锁定，直到事务块结束，这意味着将阻止其他事务更改或获取锁定。
                goods = Goodsku.objects.select_for_update().get(pk=sku, isDelete=False, isGround=True)
            except Goodsku.DoesNotExist:
                transaction.savepoint_rollback(sid)
                return JsonResponse({"code": 6, "errmsg": "商品不存在!"})
            # 获取redis中商品数量
            try:
                count = int(r.hget(cart_key, sku))
            except:
                transaction.savepoint_rollback(sid)
                return JsonResponse({"code": 7, "errmsg": "参数错误!"})
            # 判断库存是否足够
            if goods.stock < count:
                transaction.savepoint_rollback(sid)
                return JsonResponse({"code": 8, "errmsg": "商品库存不足!"})
            # 保存到订单商品表
            OrderGoods.objects.create(order_id=order, sku_id=goods, good_num=count, good_price=goods.price)
            # 改变销量与库存
            goods.stock -= count
            goods.sale_num += count
            goods.save()
            # 计算总价
            order_amount += goods.price * count
        # 计算总金额
        try:
            order.order_amount = order_amount
            order.save()
        except:
            transaction.savepoint_rollback(sid)
            return JsonResponse({"code": 9, "errmsg": "保存总金额失败!"})
        # 删除购物车中的商品
        r.hdel(cart_key, *sku_ids_int)

        # 成功
        # 提交事务
        transaction.savepoint_commit(sid)
        return JsonResponse({"code": 0, "msg": "成功!", "order_num": order_num})


# 支付订单页面
class Order(BaseVerifyView):
    def get(self, request):
        # 接受数据
        user_id = request.session.get("ID")
        order_num = request.GET.get("order_num")
        try:
            order = Orders.objects.get(order_num=order_num, user_id=user_id)
        except Orders.DoesNotExist:
            return redirect("cart:cart")
        # 计算总价
        total = float(order.order_amount) + float(order.transport_price)
        url = ""
        context = {
            "order": order,
            "total": total,
            "url": url
        }
        return render(request, "allorder/order.html", context)

    def post(self, request):
        pass


# 发起支付宝支付
@verify_login_required
def pay(request):
    # 获取参数
    order_num = request.GET.get("order_num")
    user_id = request.session.get("ID")
    # 查询订单
    try:
        order = Orders.objects.get(order_num=order_num, user_id=user_id, status=0)
    except Orders.DoesNotExist:
        return redirect("goods:首页")

    app_private_key_string = open(os.path.join(settings.BASE_DIR, "apps/allorder/private_key.txt")).read()
    alipay_public_key_string = open(os.path.join(settings.BASE_DIR, "apps/allorder/public_key.txt")).read()
    alipay = AliPay(
        appid="2016092300577117",  # 应用id
        app_notify_url=None,  # 默认回调url
        app_private_key_string=app_private_key_string,

market/templates/allorder/gladdress.html
{% extends "public/base.html" %}
{% load static %}
{% block main %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="{% url 'users:member' %}" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">管理收货地址</a>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="{% url 'allorder:address' %}" class="">
                <i class="am-icon-plus"></i>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
    <ul class="address-list">
        {% for d in data %}
            <li data_id="{{ d.pk }}" {% if d.isDefault %}class="curr"{% endif %}>
                <p>收货人：{{ d.username }}&nbsp;&nbsp;{{ d.phone }}</p>
                <p class="order-add1">收货地址：{{ d.hcity }} {{ d.hproper }} {{ d.harea }} {{ d.brief }}</p>
                <hr/>
                <div class="address-cz">
                    <label class="am-radio am-warning">
                        <input class="defa" type="radio" name="radio3" {% if d.isDefault %}checked{% endif %}
                               data-am-ucheck> 设为默认
                    </label>
                    <a href="{% url 'allorder:editAddress' d.pk %}">
                        <img src="{% static 'images/bj.png' %}" width="18"/>&nbsp;编辑
                    </a>
                    <a href="javascript:;" class="del">删除</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}
{% block foot_js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>
    <script>
        $(function () {
            // 点击删除,删除此收货地址
            $(".del").on("click", function () {
                //console.debug(11);
                var li = $(this).parents("li");
                var id = li.attr("data_id");
                var flag = confirm("是否删除此收货地址?");
                if (flag == true) {
                    li.remove();
                    $.ajax({
                        type: "post",
                        url: "{% url 'allorder:delAddress' %}",
                        data: {
                            "id": id,
                            "csrfmiddlewaretoken": "{{ csrf_token }}",
                        },
                        dataType: "json",
                        success: function (data) {
                            if (data.code == 0) {
                                console.debug(data);
                            } else {
                                console.debug(data)
                            }
                        }
                    });
                }
            });

            // 点击设为默认,设置为默认
            $(".defa").on("click", function () {
                var li = $(this).parents("li");
                var id = li.attr("data_id");
                var flag = confirm("是否修改此地址为默认收货地址?");
                if (flag == true) {
                    // 修改成功,重新加载页面
                    location.reload();
                    $.ajax({
                        type: "post",
                        url: "{% url 'allorder:defaAddress' %}",
                        data: {
                            "id": id,
                            "csrfmiddlewaretoken": "{{ csrf_token }}",
                        },
                        dataType: "json",
                        success: function (data) {
                            if (data.code == 0) {
                                console.debug(data);
                            } else {
                                console.debug(data)
                            }
                        }
                    });
                } else {
                    location.reload()
                }
            });
        })
    </script>
{% endblock %}

market/templates/allorder/order.html
{% extends 'public/base.html' %}
{% load static %}

{% block main %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">确认订单</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <h5 class="order-tit">收货人信息</h5>
    <div class="order-name">
        <p class="order-tele">{{ order.name }}&nbsp;&nbsp;&nbsp;{{ order.phone }}</p>
        <p class="order-add">{{ order.address }}</p>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <h5 class="order-tit">确认订单信息</h5>
    <ul class="shopcart-list" style="padding-bottom: 0; margin-top: 0;">
        {% for og in order.ordergoods_set.all %}
            <li>
                <img src="{{ MEDIA_URL }}{{ og.sku_id.logo_url }}" class="shop-pic"/>
                <div class="order-mid">
                    <div class="tit">{{ og.sku_id.good_id.name }}{{ og.sku_id.name }}</div>
                    <div class="order-price">￥{{ og.good_price }} <i>X{{ og.good_num }}</i></div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <ul class="order-infor">
        <li class="order-infor-first">
            <span>商品总计：</span>
            <i>￥{{ order.order_amount }}</i>
        </li>
        <li class="order-infor-first">
            <span>运输方式：{{ order.transport }}</span>
            <i>¥<span>{{ order.transport_price }}</span></i>
        </li>
        <li>付款方式:</li>
    </ul>
    <ul class="pay-style">
        <li>
            <img src="{% static 'images/zhi.png' %}" width="50"/>
            <span>
		   	 		<p>支付宝</p>
		   	 		<p class="descript">推荐有支付宝账号的用户使用</p>
		   	 	</span>
            <label class="am-radio-inline">
                <input type="radio" checked="checked" name="radio10" value="1" data-am-ucheck>
            </label>
        </li>
        <li>
            <img src="{% static 'images/wei.png' %}" width="50"/>
            <span>
		   	 		<p>微信支付</p>
		   	 		<p class="descript">推荐安装微信5.0及以上版本的使用</p>
		   	 	</span>
            <label class="am-radio-inline">
                <input type="radio" name="radio10" value="1" data-am-ucheck>
            </label>
        </li>
    </ul>
    <div style="background: #eee; height: 10px;"></div>
    <p style="padding-left: 2rem">备注: <span>{{ order.comment }}</span></p>
    <div style="background: #eee; height: 10px;"></div>
    <div style="height: 55px;"></div>
    <div class="shop-fix">
        <div class="order-text">
            应付总额：<span>￥{{ total }}</span>
        </div>
        <a href="{% url 'allorder:pay' %}?order_num={{ order.order_num }}" class="js-btn">确认支付</a>
    </div>
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="../message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:cart' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'allorder:订单' %}" class="curr">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'users:member' %}" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

market/templates/allorder/pay.html
{% extends 'public/base.html' %}
{% load static %}

{% block main %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">完成支付</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <ul class="order-detail">
        <li><span>支付结果：</span>{{ message }}</li>
    </ul>
    <a href="{% url 'allorder:订单' %}">
        <input type="button" class="login-btn" value="查看订单">
    </a>
{% endblock %}

{% block foot_js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>
{% endblock %}

market/templates/allorder/tureorder.html
{% extends 'public/base.html' %}
{% load static %}

{% block main %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">提交订单</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <form action="" method="post" id="order_form">
        {% csrf_token %}
        {% if not address %}
            <div class="add-address">
                <a href="address.html">+新建收货地址</a>
                <i class="am-icon-angle-right"></i>
            </div>
        {% else %}
            <h5 class="order-tit">收货人信息</h5>
            <input type="hidden" name="address_id" value="{{ address.pk }}">
            <div class="order-name">
                <a href="{% url 'allorder:gladdress' %}">
                    <p class="order-tele">{{ address.username }}&nbsp;&nbsp;&nbsp;{{ address.phone }}</p>
                    <p class="order-add">
                        {{ address.hcity }}
                        {{ address.hproper }}
                        {{ address.harea }}
                        {{ address.brief }}
                    </p>
                </a>
                <i class="am-icon-angle-right"></i>
            </div>
        {% endif %}
        <div style="background: #eee; height: 10px;"></div>
        <ul class="shopcart-list" style="padding-bottom: 0;">
            {% for good in goodskus %}
                <input type="hidden" name="sku_id" value="{{ good.pk }}">
                <li>
                    <img src="{{ MEDIA_URL }}{{ good.logo_url }}" class="shop-pic"/>
                    <div class="order-mid">
                        <div class="tit">{{ good.good_id.name }}{{ good.name }}</div>
                        <div class="order-price">￥{{ good.price }} <i>X{{ good.count }}</i></div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <ul class="order-infor">
            <li class="order-infor-first">
                <span>商品总计：</span>
                <i>￥<span id="goods_price">{{ total_price }}</span></i>
            </li>
            <li class="order-infor-first">
                <span>运输方式：</span>
                <i>
                    <select name="transport" id="transport">
                        {% for tran in transport %}
                            <option value="{{ tran.pk }}" price="{{ tran.money }}">
                                {{ tran.name }}-￥<i>{{ tran.money }}</i>
                            </option>
                        {% endfor %}
                    </select>
                </i>
            </li>
        </ul>
        <div style="background: #eee; height: 10px;"></div>
        <div style="background: #eee; height: 10px;"></div>
        <textarea placeholder="备注说明" class="bz-infor" name="comment"></textarea>
        <div style="height: 55px;"></div>
        <div class="shop-fix">
            <div class="order-text">
                应付总额：<span>￥<span id="sum_price">0.00</span></span>
            </div>
            <a href="javascript:;" class="js-btn">提交订单</a>
        </div>
    </form>
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="../message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:cart' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'allorder:订单' %}" class="curr">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'users:member' %}" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block foot_js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>
    <script>
        $(function () {
            // 设置计算价格函数
            function totalPrice() {
                var goods_price = $("#goods_price").text();
                var trans_price = $("#transport").find(":selected").attr("price");
                var total = parseFloat(goods_price) + parseFloat(trans_price);
                $("#sum_price").text(total.toFixed(2));
            }

            // 调用
            totalPrice();

            // 运输方式改变价格
            $("#transport").on("change", function () {
                totalPrice()
            });

            // 绑定提交订单点击事件
            $(".js-btn").on("click", function () {
                //准备数据
                var data = $("#order_form").serialize();
                console.debug(data);
                $.ajax({
                    type: "post",
                    url: "{% url 'allorder:tureorder' %}",
                    dataType: "json",
                    data: data,
                    success: function (data) {
                        if (data.code == 0) {
                            location.href = "{% url 'allorder:order' %}?order_num=" + data.order_num
                        } else {
                            alert("生成订单失败,请稍后再试!")
                        }
                    }
                });
            });
        })
    </script>
{% endblock %}